### ISSUE TITLE
Ability to refresh view as I draw

### ISSUE THREAD

**Issue by mrandrey** [onyx-intl/OnyxAndroidSample#101]
Hello,

From what I understand, once I call touchHelper.setRawDrawingEnabled(true), the view stops refreshing. Is there a way to prevent that behavior? I'd like to both draw and have the refresh of the view below for my app's functionality.

Presently, I can keep calling touchHelper.setRawDrawingEnabled(false); touchHelper.setRawDrawingEnabled(true), on every stroke end, but that behaves erratically, as I imagine it's resource intensive.

Thanks,
Andrey

P.S. I'm working on a Note.

**Comment by joycode** [comment]
For fast drawing, we have to stop screen refreshing, you can try to call touchHelper.setRawDrawingEnabled(false) in a delayed time, if there is new writings during the time, you can just cancel the call to avoid the cost.
