### ISSUE TITLE
touchPoint.getSize() is always 0

### ISSUE THREAD

**Issue by LanmanGroup** [onyx-intl/OnyxAndroidSample#103]
in this sample https://github.com/onyx-intl/OnyxAndroidSample/blob/master/app/sample/src/main/java/com/onyx/android/sample/PenStylusTouchHelperDemoActivity.java 
in `RawInputCallback`, `touchPoint.getSize()` is always `0`. 
 The correct value should will be same as stroke width....or not?

**Comment by qiujiejun** [comment]
The raw input is only contained x, y and pressure. There is no size info here, so, it is zero.

**Comment by LanmanGroup** [comment]
ok, what do you think about add a method `setSize` in `TouchPoint` class?

**Comment by LanmanGroup** [comment]
...i saw now that there is `set(TouchPoint point)` function. I try this and let you know

**Comment by LanmanGroup** [comment]
`setSize` is useful

**Comment by LanmanGroup** [comment]
ok, i try to manually update `TouchPoint`
