### ISSUE TITLE
PenReader (Onyx Scribble SDK) VS Bluetooth device

### ISSUE THREAD

**Issue by LanmanGroup** [onyx-intl/OnyxAndroidSample#17]
When I connect a bluetooth device, like a pedal, the pen doesn't work anymore.

In [ScribbleStylusDemoActivity](https://github.com/onyx-intl/OnyxAndroidSample/blob/master/app/sample/src/main/java/com/onyx/android/sample/ScribbleStylusDemoActivity.java) I can't take scribble notes, while in [ScribbleTouchScreenDemoActivity](https://github.com/onyx-intl/OnyxAndroidSample/blob/master/app/sample/src/main/java/com/onyx/android/sample/ScribbleTouchScreenDemoActivity.java) I can.

**Comment by qiujiejun** [comment]
Could you please describe in more detail? Cannot take note only during the BT connection? can take notes after connected?
  A video would explain everything. Please help to provide it. Thanks.

**Comment by qiujiejun** [comment]
BTW, we suggest that the third-party app which uses onyxsdk-scribble should full-screen in order to make writing not interrupted by screen refresh of status bar.

**Comment by LanmanGroup** [comment]
This is the video https://goo.gl/photos/GLBfmgTFrgnr19cy9.
1. We used a BT pedal that in the video is already paired with MAX 
2. We launched OnyxAndroidSample
3. In ScribbleStylusDemoActivity MAX did not capture the note
4. In ScribbleTouchScreenDemoActivity MAX captured the note
5. We turned off the BT
6. In both ScribbleStylusDemoActivity and ScribbleTouchScreenDemoActivity the MAX captured the note

**Comment by qiujiejun** [comment]
Hi, Please use the new version:
compile 'com.onyx.android.sdk:onyxsdk-scribble:1.0.3'
this version resolves this issue.

**Comment by LanmanGroup** [comment]
Hi, 
sorry but now in `ScribbleStylusDemoActivity` MAX did not capture the note, same with BT on or off.

**Comment by LanmanGroup** [comment]
with sdk-base:1.3.1 & scribble:1.0.3 works good
