### ISSUE TITLE
Scribble on MaxCarta

### ISSUE THREAD

**Issue by LanmanGroup** [onyx-intl/OnyxAndroidSample#36]
on MaxCarta, **stylus scribble demo** and **touch screen scribble demo** are very slow!
Have you a new version of onyxsdk-scribble?

**Comment by LanmanGroup** [comment]
Hi @qiujiejun, 
Did you check this issue?

**Comment by qiujiejun** [comment]
Hi. Let me take a video for this. To check if we are on the "same page".

**Comment by LanmanGroup** [comment]
Ok, let me know.
This is my sample https://drive.google.com/open?id=0Bxk8JrIx087WaF94N29mQlYxcm8

**Comment by qiujiejun** [comment]
Please check my sample:
https://mega.nz/#!0V9UABYL!g4M-camEQ4aI5Mx7xMA-21eLJE8plM-QwLKy9tDGWE0

**Comment by qiujiejun** [comment]
please upload to the other host service if you can. we can not access google drive recently.

**Comment by LanmanGroup** [comment]
ok, i saw your video. The problem is in stylus **scribble demo** and **touch screen scribble demo** of this repo. With the apps pre-installed in MaxCarta all works good.
I'm developing and app based on onyxsdk-scribble and  the scribble is very slow.

**Comment by LanmanGroup** [comment]
https://mega.nz/#!p4sinC5Y!PvmuKJaIlVHxNXRTsGak1M8ULsUJfr7K3uQjJQOBBec

**Comment by LanmanGroup** [comment]
Hi, any news? Thank you

**Comment by LanmanGroup** [comment]
I saw the last updates, but the problem is still there...

**Comment by rcarcasses** [comment]
Is there any chance that we can contribute to the pre-installed version in Max Carta? I think is not slow but I truly believe the erasing capability is extremely bad, which makes the writing experience sometimes stressful. Is the code available?

Thanks!

**Comment by joycode** [comment]
close as we switched to onyxsdk-pen
