### ISSUE TITLE
Strage refresh

### ISSUE THREAD

**Issue by LanmanGroup** [onyx-intl/OnyxAndroidSample#41]
If I press five (or more) times Hardware button (Menu or page up/down) the screen refresh.

Check this
https://mega.nz/#!soVDnLrB!bYs32U5JhXDXmyzwvJFBR0vpF4tltFBvMqbhgGMGOOw

PS same in an empty app with an empty activity.

**Comment by qiujiejun** [comment]
Could you please take a photo of the "Settings -> About -> About device"? I need to check in which android version of the firmware.

**Comment by qiujiejun** [comment]
This refresh is intentional. We will remove it after we create a tailor-made model for you in the future order firmware.

**Comment by LanmanGroup** [comment]
Android 4.0.4, firmware 1.8.2.
Ok, thank you!
